### ISSUE TITLE
doesnt even allow to start plugin

### ISSUE THREAD

**Issue by mcyanny** [HotFireyDeath/Glifcos#10]
[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Server::getServerName()" (EXCEPTION) in "/glifcos-plugin/src/Glifcos/Glifcos" at line 57

**Comment by Patra3** [comment]
What version of PocketMine/Genisys/build are you using?
Whatever version you used doesn't have the required getServerName() method. I tested this on Genisys and it works fine, but if this method doesn't exist for PocketMine, I'll fix it asap.

Sorry for the inconvenience, I will also perform further testing on this error.

**Comment by mcyanny** [comment]
c1ea9cc
Genisys

**Comment by Patra3** [comment]
Thank you for the issue report!
I've done some testing on your version and it is in fact an error!

I've fixed this and some other issues in this new release:
https://github.com/HotFireyDeath/Glifcos/releases/tag/2.0.0-b2

Just replace your old Glifcos webserver/plugin files with the ones provided, and let me know how things are working. I hope they work well :)!

**Comment by mcyanny** [comment]
thx
