### ISSUE TITLE
Is this an issue?

### ISSUE THREAD

**Issue by mcyanny** [HotFireyDeath/Glifcos#11]
Warning: file_get_contents(http://www.myiphere/glifcos-webserver/database/commands.txt): failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.  in phar://C:/Users/Yan/Desktop/PixelFlick/plugins/Glifcos_v2.0.0-b2.phar/src/Glifcos/tasks/ConsoleCommandTask.php on line 22

Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in phar://C:/Users/Yan/Desktop/PixelFlick/plugins/Glifcos_v2.0.0-b2.phar/src/Glifcos/tasks/ConsoleCommandTask.php on line 22

**Comment by YanSoo123** [comment]
lol sorry

**Comment by Patra3** [comment]
Huh, this is most certainly strange. Glifcos plugin/PocketMine server isn't able to connect to your web server. Is the web server being hosted on the same machine as the PocketMine server, and are you accessing the web server using 'localhost' or a local ip?

You should try to access the web server with a public IP/domain that anyone can connect to globally, instead of private/local ip as Glifcos may fail.

**Comment by mcyanny** [comment]
Yes I am connecting with my external ip, and it is the same machine. ALSO SUGGESTION: make glifcos more like pocketdockconsole and host it from the pocketmine server.

**Comment by Patra3** [comment]
Thanks again for reporting, after further testing I'm appearing to also reproduce the issue.
Working on a quick fix, I'll post it real soon.

**Comment by mcyanny** [comment]
Thank you

**Comment by Patra3** [comment]
Ok, this fix will now work.
Please download and replace your web server files with the one packaged:
https://github.com/HotFireyDeath/Glifcos/releases/download/2.0.0-b2/Glifcos-webserver.tar.gz

and reset the setup process on Glifcos (delete the plugin datafolder), along with the /database folder in the web server.

Then, once you've reset the setup process (so it's back on the wizard), choose 'Use Direct IP Command', and enter the command as needed. It should fix the errors.

Thanks :) and tell me if anything else happens.
