### ISSUE TITLE
Issue number #12 ANOTHER ONE

### ISSUE THREAD

**Issue by mcyanny** [HotFireyDeath/Glifcos#12]
Warning: file_get_contents(http://myexternalip/glifcos-webserver/database/commands.txt): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in C:\Users\Yan\Desktop\PixelFlick\plugins\glifcos-plugin\src\Glifcos\tasks\ConsoleCommandTask.php on line 22

Warning: file_get_contents(http://myexternalip/glifcos-webserver/database/FILE_POINTER_PATH.txt): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in C:\Users\Yan\Desktop\PixelFlick\plugins\glifcos-plugin\src\Glifcos\tasks\FileBroadcastTask.php on line 19

I tried both the regular AND the direct ip command...

**Comment by Patra3** [comment]
Those are normal errors to be fixed soon. To fix both of these issues currently, simply send a command through the console (in Glifcos), and open/use the file manager in Glifcos. Those errors should disappear.
