### ISSUE TITLE
sys_getloadavg() not working - Windows

### ISSUE THREAD

**Issue by Patra3** [HotFireyDeath/Glifcos#2]
Glifcos plugin current has an issue with Windows only systems.
sys_getloadavg() is not a implemented function as of yet on Windows, and Glifcos is very reliant on that function for system CPU broadcasts.

Adjustments will be made in a quick update.

**Comment by HotFireyDeath** [comment]
Fixed in update 0.1-BETA. Testing may be required.

**Comment by Patra3** [comment]
It seems there are still memory issues related to Windows machines.

**Comment by Patra3** [comment]
Fixed in update 0.1.2.
