### ISSUE TITLE
Index.php errors apear

### ISSUE THREAD

**Issue by mcyanny** [HotFireyDeath/Glifcos#7]
Yellow lines appear and say

__Notice: Undefined index: HTTPS in C:\wamp64\www\glifcos-webserver\index.php on line 

I am using an Apache webserver and it works... But these errors are everywhere... Should I run RESET.php?

**Comment by Patra3** [comment]
These errors appear on the page or in the console (plugin)?

**Comment by mcyanny** [comment]
They appear on the webpage... Is HackScreen.php the reason why... because my directory is

_http://localhost/glifcos-webserver/library/main/hack_screen.php

**Comment by Patra3** [comment]
It appears that your webserver doesn't support some settings for Glifcos (specifically the HTTPS key)...

**Comment by mcyanny** [comment]
Is this something I can fix?

**Comment by Patra3** [comment]
Not currently. Either try a different webserver (supporting HTTPS), or wait for 2.0.

**Comment by Patra3** [comment]
All issues are now fixed in the 2.0 release.
https://github.com/HotFireyDeath/Glifcos/releases/tag/2.0.0-b1
