### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by daniktheboss** [HotFireyDeath/Glifcos#8]
Console tells me lots of errors.
Using latest glifcos 2.0

**Comment by Patra3** [comment]
Proceed as expected, just ignore the errors and go into index.html and enter the command into the console.
Then, make the account and log into Glifcos. The errors should no longer appear after that (if they go give the server another refresh).

**Comment by daniktheboss** [comment]
Ok will try.. keep fingers crossed

**Comment by daniktheboss** [comment]
Keeps on saying server not connected

**Comment by Patra3** [comment]
On the index.html page? Hmm..

Did you /stop and open your server (don't use /reload)?
Did you refresh the index.html page?

**Comment by daniktheboss** [comment]
Yes I did stop and I have loop= on linux
