### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [HotFireyDeath/Glifcos#9]
I 've entered the necessary commands and server restart . But I encounter these errors . What should I do?

Warning: file_get_contents(http://www.turkmcpe.net/admin/): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Temporarily Unavailable
 in phar://C:/Users/ozgur/Desktop/TurkMCPE/TurkMCPE-TEST/plugins/Glifcos_v2.0.0-b1.phar/src/Glifcos/tasks/ConsoleCommandTask.php on line 19

Warning: Invalid argument supplied for foreach() in phar://C:/Users/ozgur/Desktop/TurkMCPE/TurkMCPE-TEST/plugins/Glifcos_v2.0.0-b1.phar/src/Glifcos/tasks/ConsoleCommandTask.php on line 22

Warning: file_get_contents(http://www.turkmcpe.net/admin/): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Temporarily Unavailable
 in phar://C:/Users/ozgur/Desktop/TurkMCPE/TurkMCPE-TEST/plugins/Glifcos_v2.0.0-b1.phar/src/Glifcos/tasks/FileBroadcastTask.php on line 16

**Comment by Patra3** [comment]
It could be because of your CloudFlare protection, can you try to disable the CloudFlare/bot protection and try again? Remember to enter the command that shows up on the index.html page.

**Comment by ghost** [comment]
I try not to CloudFlare site gave error , but this one could not connect to the site server. There was no error on the console .

**Comment by ghost** [comment]
how to fix?

**Comment by Patra3** [comment]
If you use CloudFlare or other bot protection, it will cause Glifcos to fail. You must disable all protection first.

**Comment by ghost** [comment]
I did what the problem continues , please help me to solve this problem.
